### PR TITLE
Suggested documentation changes

### PR DESCRIPTION
**Pull request by tvogel8570**

### CODE REVIEW

**Comment by tvogel8570** [comment]
You're welcome.

Your English is infinitely better than my French!

I'm glad the keycloak section is useful.  Adding details from SO is a great idea.

Timothy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ch4mpy** [comment]
@tvogel8570 will you fix the points I commented or should I add a commit to your PR?

**Comment by tvogel8570** [comment]
I will review later today and update the PR.
________________________________

**Review by tvogel8570 — COMMENTED** [review]
Should be "These starters".  Other than that looks good.  If I didn't update correctly, please fix and commit.

**Review by ch4mpy — APPROVED** [review]

**Pull request merged**
