### PR TITLE
implement keycloak in docker for tutorial

### PR DESCRIPTION
**Pull request by tvogel8570**
I try to leverage docker as much as possible to keep current versions of software and reduce the impact of locally installed development software.  This PR has the setup to use a dockerized Keycloak for the tutorials.  

Note this is my very first PR on any project so please give me any feedback to improve.

### CODE REVIEW

**Comment by ch4mpy** [comment]
I have to think a bit about his one: on the one hand, the aim of this repo is not to illustrate every possible deployment of every OIDC authorization server, but on the other hand, I'm not sure I ever read a short tutorial for setting up a local development Keycloak instance on Docker with a self-signed SSL certificate.

If we add this one, we should probably add one for K8s too (for instance using Docker-Desktop one)...

What do you think of creating such tutorials on your own Github account and modifying this PR to contain only links to your own repo(s)?

**Comment by tvogel8570** [comment]
I created a public GitHub repo for this solution.  It is [here](https://github.com/tvogel8570/samples/tree/main/infrastructure/keycloak).  

I've never worked with K8s / swarm.  I'll look to add it in the future.

I'm not sure how to modify this PR to best work on your site.  Please make a recommendation how you think this PR should be revised or add a link to my repo in the appropriate place.

**Comment by ch4mpy** [comment]
I was thinking of removing what you put under `infrastructure` and editing the Keycloak README (the `/samples/tutorials/keycloak.md`) to insert links to your own tutorial(s) with a short description of the target deployment (docker running on localhost with self-signed certificate, or whatever else you provide).

What do you think?

**Comment by ch4mpy** [comment]
Replaced this PR with the following content in Keycloak tutorials README:

## 2. Keycloak in docker
You may refer to the [official documentation](https://www.keycloak.org/server/containers) or to [this tutorial](https://github.com/tvogel8570/samples/tree/main/infrastructure/keycloak) written by Timothy Vogel (who also contributed to improve this repo documentation)

**Pull request closed without merging**
